import Head from 'next/head'
import useChangeCurrent from '@/hooks/useChangeCurrent'

export default function Home() {
   const {fonts} = useChangeCurrent();
   const {normalBarlow,bellefair,barlow} = fonts
  return (
    <>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
       <section className={`${barlow.variable} font-barlow  lg:my-auto text-3xl  flex justify-between home  lg:px-12 lg:ml-20 px-6 flex-col lg:flex-row items-center  lg:gap text-secondary gap-20 flex-1 lg:items-end `}>
        <div className='max-w-md  flex flex-col md:gap-6 flex-1'>
          
        <h1 className={` page-title text-secondary`}>
        SO, YOU WANT TO TRAVEL TO <br/>
          <span className={`font-belleFair ${bellefair.variable}  text-white lg:text-9xl md:text-8xl text-7xl lg:leading-lg leading-[150px]`}>space</span>
        </h1>
        <p className={`${normalBarlow.variable} page-description `}> Let’s face it; if you want to go to space, you might as well genuinely go to outer space and not hover kind of on the edge of it. Well sit back, and relax because we’ll give you a truly out of this world experience!</p>
        </div>
        <div className='flex-1 hidden lg:block'></div>
        <div className={` ${bellefair.variable} large-btn flex-1`}>Explore</div>
        <div className='hidden lg:block'></div>
       </section>

    </>
  )
}
